development:
  adapter:  postgresql
  encoding: utf8
  host:     <%= ENV['DATABASE_HOST'] %> 
  username: synopticly
  password: <%= ENV['DATABASE_PASS'] %> 
  port:     <%= ENV['DATABASE_PORT'] %>
  database: synopticly
  pool:     20

  
